# Generated by Django 3.0.6 on 2020-05-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20200517_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.URLField(blank=True, default='https://joyfulharmony.org/wp16/wp-content/uploads/2018/03/No-Movies-For-Two-Years.jpg', null=True),
        ),
    ]
