# Generated by Django 3.0.6 on 2020-05-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20200517_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.URLField(blank=True, max_length=900, null=True),
        ),
    ]
